44 publish version 100 v3 (#73)
* license and contribution md files added

* workflow update - copy changelog into dist on publish

* workflow update - changesets validation moved

diff --git a/.github/workflows/npm-publisher.yml b/.github/workflows/npm-publisher.yml
--- a/.github/workflows/npm-publisher.yml
+++ b/.github/workflows/npm-publisher.yml
@@ -56,6 +56,13 @@ jobs:
         with:
           node-version: 20
 
+      - name: Check for changesets
+        run: |
+          if [ ! -d ".changeset" ] || [ -z "$(find .changeset -type f -name '*.md' ! -name 'README.md')" ]; then
+            echo "No valid changesets found. Cannot publish."
+            exit 1
+          fi
+
       - name: Install dependencies
         run: npm ci
 
