license and contribution md files added (#72)
* license and contribution md files added

* workflow update - copy changelog into dist on publish

diff --git a/.github/workflows/npm-publisher.yml b/.github/workflows/npm-publisher.yml
--- a/.github/workflows/npm-publisher.yml
+++ b/.github/workflows/npm-publisher.yml
@@ -7,13 +7,20 @@ permissions:
   contents: write
 
 jobs:
-  unit-test:
-    name: Run Unit Tests
+  check-requirements:
+    name: Check all requirements
     runs-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [18, 20, 22] # Test on Node.js versions 18, 20, and 22
     steps:
+      - name: Check for changesets
+        run: |
+          if [ ! -d ".changeset" ] || [ -z "$(find .changeset -type f -name '*.md' ! -name 'README.md')" ]; then
+            echo "No valid changesets found. Cannot publish."
+            exit 1
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
@@ -28,10 +35,13 @@ jobs:
       - name: Run unit tests
         run: npm test
 
+      - name: Build project
+        run: npm run build
+
   version-bump:
     name: Version Bump PR
     runs-on: ubuntu-latest
-    needs: unit-test
+    needs: check-requirements
     outputs:
       pr_number: ${{ steps.create-pr.outputs.pull-request-number }}
 
@@ -92,6 +102,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -103,20 +115,23 @@ jobs:
         run: npm ci
 
       - name: Build project
-        run: npm run build
+        run: npm run build && cp CHANGELOG.md dist/
 
       - name: Publish package to npm
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
         run: |
           PACKAGE_NAME=$(jq -r .name package.json)
+          PACKAGE_VERSION=$(jq -r .version package.json)
 
           if [[ "$PACKAGE_NAME" == @* ]]; then
             echo "Scoped package detected. Publishing with --access=restricted..."
-            npm publish --access=restricted
+            npm publish --access=restricted --tag "$PACKAGE_VERSION"
+            npm dist-tag add "$PACKAGE_NAME@$PACKAGE_VERSION" --tag latest
           else
             echo "Unscoped package detected. Publishing without --access=restricted..."
-            npm publish
+            npm publish --tag "$PACKAGE_VERSION"
+            npm dist-tag add "$PACKAGE_NAME@$PACKAGE_VERSION" --tag latest
           fi
 
   # notify-slack:
